vmsim: vmsim.c wsclock.c wsclock.h aging.c aging.h clock.c clock.h opt.c opt.h page.c page.h queue.c queue.h uthash.h
	gcc -o vmsim vmsim.c wsclock.c wsclock.h aging.c aging.h clock.c clock.h opt.c opt.h page.c page.h queue.c queue.h uthash.h
